# Generated by Django 3.2.5 on 2021-07-06 18:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('year_joined', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('photo', models.ImageField(default='images/default.png', upload_to='images/profile_pics')),
            ],
        ),
    ]
